name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      jar_basename: ${{ steps.jar_details.outputs.jar_basename }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Determine JAR details
      id: jar_details
      run: |
        JAR_FULL_PATH=$(ls target/HttpHistoryTabs-*-jar-with-dependencies.jar)
        echo "JAR_UPLOAD_PATH=${JAR_FULL_PATH}" >> $GITHUB_ENV
        echo "jar_basename=$(basename "${JAR_FULL_PATH}")" >> $GITHUB_OUTPUT
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: ${{ env.JAR_UPLOAD_PATH }}

  release: 
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: package
          path: staging

      - name: Create Release and Upload JAR
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }} (commit ${{ github.sha }})
          generate_release_notes: true
          files: staging/${{ needs.build.outputs.jar_basename }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 